target: modules.state_utils.MyTrainState
Input_Shape: [ [ 1,224,224,3 ], ]
Model:
  target: model.ViT_test2.ViT_T
  params:
    num_classes: 1000
Optimizer:
  target: optax.adamw
  params:
    learning_rate: 1.0e-3
    weight_decay: 0.001
