target: modules.state_utils.MyTrainState
Input_Shape: [ [ 1,224,224,3 ], ]
Model:
  target: model.ResNet.ResNet50
  params:
    num_classes: 1000
Optimizer:
  target: optax.lion
  params:
    learning_rate: 3.0e-4
    weight_decay: 1
