
target: modules.state_utils.MyTrainState
Input_Shape: [ [ 1,224,224,3 ], ]
Model: 
  target: model.VGG.VGG16
  params:
    num_classes: 1000
Optimizer:
  target: optax.adamw
  params:
    learning_rate: 4.0e-4
    weight_decay: 0.001
