{
  "train": {
      image_size: 224,
      batch_size: 1024,
      shuffle_size: 2000000,
      data_path: 'gs://jtitor-eu/data/tensorflow_datasets',
      seed: 43,
      total_epoch: 100,
      model_path: 'check_points'
  },
  "State": {
    target: modules.state_utils.MyTrainState,
    Input_Shape: [ [ 1,224,224,3 ], ],
    Model: {
      target: model.RepVGG.RepVGG_B2,
      params: {
        num_classes: 1000
      }
    },
    Optimizer: {
      target: optax.sgd,
      params: {
        learning_rate: 0.4,
        nesterov: True,
        momentum: 0.9
#        b1: 0.9,
#        b2: 0.99,
#        weight_decay: 1
      }
    },
  },

}