{
  "train": {
      image_size: 224,
      batch_size: 32,
      shuffle_size: 20000,
      data_path: '/home/john/tensorflow_datasets',
      seed: 43,
      total_epoch: 90,
      model_path: 'check_points',
      cut_mix: True
  },
  "State": {
    target: modules.state_utils.MyTrainState,
    Input_Shape: [ [ 1,224,224,3 ], ],
    Model: {
#      target: model.PoolFormer.ViT_T,
      target: model.ViT.ViT_S,
      params: {
        num_classes: 1000
      }
    },
    Optimizer: {
      target: optax.adamw,
      params: {
        learning_rate: 1.0e-4,
        b2: 0.98
      }
    },
  },

}