train:
    image_size: 224,
    batch_size: 1024,
    shuffle_size: 1000000,
    data_path: 'gs://jtitor-eu/data/tensorflow_datasets',
    seed: 43,
    total_epoch: 300,
    warmup_epoch: 40,
    model_path: 'check_points'


